package gals;

public interface Constants extends ScannerConstants, ParserConstants
{
    int EPSILON  = 0;
    int DOLLAR   = 1;

    int t_NEW_LINE = 2;
    int t_BREAK = 3;
    int t_COMMA = 4;
    int t_STRUCTURE_REFERENCE = 5;
    int t_COLON = 6;
    int t_RETURN = 7;
    int t_IN = 8;
    int t_NULL = 9;
    int t_FUNCTION_RETURN = 10;
    int t_SCOPE_OPEN = 11;
    int t_SCOPE_CLOSE = 12;
    int t_SUBGROUP_OPEN = 13;
    int t_SUBGROUP_CLOSE = 14;
    int t_INDEX_OPEN = 15;
    int t_INDEX_CLOSE = 16;
    int t_MAIN_FUNCTION = 17;
    int t_PRINT = 18;
    int t_INPUT = 19;
    int t_RANGE = 20;
    int t_VAR = 21;
    int t_CONST = 22;
    int t_FUNCTION = 23;
    int t_IF = 24;
    int t_ELSE = 25;
    int t_ELSIF = 26;
    int t_SWITCH = 27;
    int t_CASE = 28;
    int t_DEFAULT = 29;
    int t_WHILE = 30;
    int t_DO = 31;
    int t_FOR = 32;
    int t_CONTINUE = 33;
    int t_TYPE_VOID = 34;
    int t_TYPE_INT = 35;
    int t_TYPE_FLOAT = 36;
    int t_TYPE_DOUBLE = 37;
    int t_TYPE_STRING = 38;
    int t_TYPE_CHAR = 39;
    int t_TYPE_BOOLEAN = 40;
    int t_INT = 41;
    int t_FLOAT = 42;
    int t_BOOLEAN = 43;
    int t_BINARY = 44;
    int t_HEXADECIMAL = 45;
    int t_STRING = 46;
    int t_CHAR = 47;
    int t_OP_ASSIGN = 48;
    int t_OP_ADD = 49;
    int t_OP_SUB = 50;
    int t_OP_MULT = 51;
    int t_OP_DIV = 52;
    int t_OP_MOD = 53;
    int t_OP_INC = 54;
    int t_OP_DEC = 55;
    int t_OP_LT = 56;
    int t_OP_LTE = 57;
    int t_OP_EQ = 58;
    int t_OP_NEQ = 59;
    int t_OP_GT = 60;
    int t_OP_GTE = 61;
    int t_OP_AND = 62;
    int t_OP_OR = 63;
    int t_OP_NOT = 64;
    int t_OP_BW_NOT = 65;
    int t_OP_BW_AND = 66;
    int t_OP_BW_OR = 67;
    int t_OP_BW_XOR = 68;
    int t_OP_BW_LS = 69;
    int t_OP_BW_RS = 70;

}
